name = "bradpitt-smp"
author = "Markus Evanger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e91b3b09a72e1f5ceb1110d13c8a867b55e30cd80b447e93f72240826657a2b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
