name = "bradpitt-smp"
author = "Markus Evanger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32ee30880576b34632daf2c0832930fd9480c80f4c62b02e52a5b2c5acf18369"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
