name = "bradpitt-smp"
author = "Markus Evanger"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acc96e6406ed1162391d7d635c62f3e296044a978895b1a234396801eff3ea9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
