name = "bradpitt-smp"
author = "Markus Evanger"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11987f955ddd39d72f37b8169583218c295d9ebb63ef62979f182a6326623d79"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
